# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pura Giri Natha
subtitle: Kota Metro
email: skdkmetro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Selamat datang di website Pura Giri Natha Kota Metro. Sebuah sarana komunikasi, berbagi dan publikasi seluruh Umat Hindu yang ada di Kota Metro, Lampung
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# twitter_username: jekyllrb
github_username:  puragirinatha

socials:
  # GitHub: https://github.com/andrewbanchich
  GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram: https://www.instagram.com/puragirinathametro/
  # LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  # Twitter: https://twitter.com/andrewbanchich
  Facebook: https://www.facebook.com/profile.php?id=100089663192663
  # Slack:


# Build settings

markdown: kramdown
sass:
  style: compressed

# theme: minima
remote_theme: sukadukametro/forty-jekyll-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
